global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:5000']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:6000']
